=== Chirili/DAW/LMSGI/XSD/Boletin1-Ejercicio6/Boletin1_Ejercicio6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="editoriales">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"></xs:element>
                <xs:element ref="editorial"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="editorial">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"></xs:element>
                <xs:element name="nombre" type="xs:string"></xs:element>
                <xs:element name="email" type="xs:string"></xs:element>
                <xs:element name="homepage" type="xs:string"></xs:element>
                <xs:element name="direccion" type="xs:string"></xs:element>
                <xs:element name="tfno" type="xs:string"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Chirili/DAW/LMSGI/XSD/Boletin1-Ejercicio6/Boletin1_Ejercicio6.xml
<?xml version="1.0" encoding="UTF-8"?>

<editoriales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Boletin1_Ejercicio6.xsd">
    <titulo></titulo>
    <editorial>
        <titulo></titulo>
        <nombre></nombre>
        <email></email>
        <homepage></homepage>
        <direccion></direccion>
        <tfno></tfno>
    </editorial>
</editoriales>
