=== Chirili/DAW/LMSGI/XSD/Boletin1-Ejercicio9/banco_sevilla.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="banco">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="sucursal"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="sucursal">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cuenta_corriente" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
            <xs:attribute name="id" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="cuenta_corriente">
        <xs:complexType>
            <xs:sequence>
               <xs:element ref="cliente" maxOccurs="unbounded"></xs:element> 
            </xs:sequence>
            <xs:attribute name="id" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="cliente">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="operaciones"></xs:element>
                <xs:element ref="cuentas"></xs:element>
                <xs:element name="prestamo" type="xs:string" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
            <xs:attribute name="nif" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="operaciones">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="operacion" type="xs:string"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="cuentas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cuenta"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="cuenta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="privilegios" type="xs:string"></xs:element>
                <xs:element name="domiciliaciones" type="xs:string"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Chirili/DAW/LMSGI/XSD/Boletin1-Ejercicio9/banco_sevilla.xml
<?xml version="1.0" encoding="UTF-8"?>

<banco  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="banco_sevilla.xsd">
    <sucursal id="">
        <cuenta_corriente id="">
            <cliente nif="">
                <operaciones>
                    <operacion></operacion>
                </operaciones>
                <cuentas>
                    <cuenta>
                        <privilegios></privilegios>
                        <domiciliaciones></domiciliaciones>
                    </cuenta>
                </cuentas>
                <prestamo></prestamo>
            </cliente>
        </cuenta_corriente>
    </sucursal>
</banco>
